apiVersion: batch/v1
kind: Job
metadata:
  name: "builder-queue"
spec:
  parallelism: 4
  template:
    spec:
      containers:
      - name: builder-queue
        image: ghcr.io/orihoch/k8s-ci-processing-jobs-builder-queue
        args: ["--rq-worker"]
        env:
          - name: TOKEN
            value: "$GITHUB_TOKEN"
          - name: RQ_REDIS_HOST
            value: "redis"
      restartPolicy: OnFailure
