name: CI
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_USER: orihoch
        IMAGE_PATH: build
        IMAGE_NAME: k8s-ci-processing-jobs-example-build
      run: |
        BUILD_ARGS=""
        if docker pull "ghcr.io/${REPO_USER}/${IMAGE_NAME}:latest"; then
          BUILD_ARGS="--cache-from ghcr.io/${REPO_USER}/${IMAGE_NAME}:latest"
        fi
        docker build -t ${IMAGE_NAME} $BUILD_ARGS $IMAGE_PATH &&\
        echo "${GITHUB_TOKEN}" | docker login https://ghcr.io -u ${REPO_USER} --password-stdin &&\
        docker tag ${IMAGE_NAME} "ghcr.io/${REPO_USER}/${IMAGE_NAME}:${GITHUB_SHA}" &&\
        docker push "ghcr.io/${REPO_USER}/${IMAGE_NAME}:${GITHUB_SHA}" &&\
        if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
          docker tag ${IMAGE_NAME} "ghcr.io/${REPO_USER}/${IMAGE_NAME}:latest" &&\
          docker push "ghcr.io/${REPO_USER}/${IMAGE_NAME}:latest"
        fi
